# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d96b827920c8f8795402aa1a6260b34bcc6f781e052e2a97c13880dd8f97dc41aa2a0c5de6ce3cfbefd5fd9188e2cde5df193391bde3466803c527d4c53f8cb9

test:
  secret_key_base: 25325f6094afa600656ea19ee26d0094f66b9c26b7892cda844fce41e1ae62039752851048b6fc192697d605d0aa6e836fa03670330059599ab7ab6edf7b0fac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
